### ISSUE TITLE
New ROCm miner

### ISSUE THREAD

**Issue by todxx** [tekcomm/AMD-rocm-rippa#3]
Hey @tekcomm, I just put out a new lyra2z miner for ROCm over [here](https://github.com/todxx/tdxminer/releases).

I was wondering if I could ask you to kick the tires on it a bit?  Maybe even get you to consider adding it to your AMD-rocm-rippa distro someday?

I know you usually mine ETH on your RX 570s(?) from the discussions in the ROCm issues section, but I promise the profits are good on this algo.  At least for now ;)

**Comment by tekcomm** [comment]
There is already the nicehash fork of sgminer compiled for nicehash with
the opencl that has lyra2z. Its included and all source is also.

**Comment by tekcomm** [comment]
The main priority is not crypto but genetic & tensor interfaces for agi.

**Comment by todxx** [comment]
Yes, a version of lyra2z is available in sgminer, but it runs at about 1/5th the hashrate.

In either case, since crypto isn't the main priority here I'll close up this issue.

**Comment by todxx** [comment]
Thanks for taking a look.  The project is actually closed source and the repo currently only has a binary release and a short readme.  The current release hasn't had much testing external testing yet, so I don't know if it's in a stable enough state to put into your release quite yet.

I had gotten the (false) impression that you were much more focused on crypto when submitting this.  I can circle back once I've gotten some more feedback on the miner and worked out any bugs found.  That is if you're still interested in including it.

**Comment by tekcomm** [comment]
I already reversed engineered it back to assembly, I would recommend you
put the dev fee on your page.

**Comment by tekcomm** [comment]
Once I get the vega this week ill test it out :)

**Comment by todxx** [comment]
Sweet, thanks for checking it out.

The dev fee is currently pretty high, as I have not decided what I want to set it to long term and it's better to start out high and go lower than the other way around.  Also to encourage people to switch to future more stable releases.  The goal of this release is to get people to kick the tires, not to switch their farm over to it.  I'll make a note of this on the page.

**Comment by tekcomm** [comment]
soon as my vega gets here ill kick the tires :)

**Comment by tekcomm** [comment]
​This is dualmining with rippa on the miltech version :) two 570's

**Comment by todxx** [comment]
I think you might have replied to the wrong thread :)

Though I wouldn't mind knowing what numbers the RX 570s get with my miner ;)

**Comment by tekcomm** [comment]
Ill run a 12 hour test this weekend
